CREATE TABLE CUSTOMERS(
CUSTOMER_ID CHAR(3),
FNAME VARCHAR(10),
LNAME VARCHAR(10),
STREET VARCHAR2(20),
CITY VARCHAR(10),
STATE CHAR(2),
ZIP VARCHAR(5),
PHONE CHAR(10),
EMAIL VARCHAR(20),
SINCE DATE,
LAST_LOGIN DATE,
CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID));


CREATE TABLE INVOICE(
INVOICE_ID CHAR(3),
INVOICE_DATE DATE,
UNIT_PRICE NUMBER(7,2),
QUANITY NUMBER(3),
DISCOUNT NUMBER(5,2),
CONSTRAINT PK_INVOICE PRIMARY KEY (INVOICE_ID));

CREATE TABLE PAYMENT(
PAYMENT_ID CHAR(3),
INVOICE_ID CHAR(3),
TYPE VARCHAR(10),
AMOUNT NUMBER(5,2),
CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID),
CONSTRAINT FK_INVOICE_PAY FOREIGN KEY(INVOICE_ID) REFERENCES INVOICE(INVOICE_ID));

CREATE TABLE EMPLOYEES(
EMPL_ID CHAR(3),
FNAME VARCHAR(10),
LNAME VARCHAR(10),
TITLE VARCHAR(10),
DOB DATE,
STREET VARCHAR2(20),
CITY VARCHAR(10),
STATE CHAR(2),
ZIP VARCHAR(5),
PHONE CHAR(10),
EMAIL VARCHAR(20),
JOIN_DATE DATE,
CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPL_ID));


CREATE TABLE ORDER(
ORDER_NO CHAR(4),
EMPL_ID CHAR(3),
ORDER_STATUS VARCHAR(10),
NO_OF_ITEM NUMBER(3),
AMOUNT NUMBER(5,2),
CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_NO),
CONSTRAINT FK_ORDER_EMPL FOREIGN KEY(EMPL_ID) REFERENCES EMPLOYEES(EMPL_ID));

CREATE TABLE DELIVERY(
DELIVERY_ID CHAR(3),
ORDER_NO CHAR(4),
TRACKING_NO VARCHAR(15),
CONSTRAINT PK_DELIVERY PRIMARY KEY (DELIVERY_ID),
CONSTRAINT FK_DELIVERY_ORDER FOREIGN KEY(ORDER_NO) REFERENCES ORDER(ORDER_NO));

CREATE TABLE SUPPLIER(
SUPPLIER_ID CHAR(3),
COMPANY_NAME  VARCHAR(20),
CONTACT_NAME  VARCHAR(20),
CONTACT_TITLE VARCHAR(20),
STREET VARCHAR2(20),
CITY VARCHAR(10),
STATE VARCHAR(10),
COUNTRY VARCHAR(10),
ZIP VARCHAR(5),
PHONE CHAR(10),
EMAIL VARCHAR(20),
FAX CHAR(10),
WEBSITE VARCHAR(30),
CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID));

CREATE TABLE PRODUCT(
PRODUCT_ID CHAR(3),
SUPPLIER_ID CHAR(3),
PRODUCT_NAME VARCHAR(20),
DESCRIPITION VARCHAR(50),
KEYWORDS VARCHAR(20),
CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
CONSTRAINT FK_PRODUCT_SUPPLY FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID));


CREATE TABLE CUST_INVO_ORD(
CUSTOMER_ID CHAR(3),
INVOICE_ID CHAR(3),
ORDER_NO CHAR(4),
CONSTRAINT PK_CUST_INVO_ORD PRIMARY KEY (CUSTOMER_ID,INVOICE_ID,ORDER_NO),
CONSTRAINT FK_CUST_INVO FOREIGN KEY(INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
CONSTRAINT FK_CUST_CUST FOREIGN KEY(CUSTOMERS_ID) REFERENCES CUSTOMERS(CUSTOMERS_ID),
CONSTRAINT FK_CUST_ORDER FOREIGN KEY(ORDER_NO) REFERENCES ORDER(ORDER_NO));

CREATE TABLE ORDER_PRODUCT(
ORDER_NO CHAR(4),
PRODUCT_ID CHAR(3),
CONSTRAINT PK_ORDER_PRODUCT PRIMARY KEY (ORDER_NO,PRODUCT_ID),
CONSTRAINT FK_OP_ORDER FOREIGN KEY(ORDER_NO) REFERENCES ORDER(ORDER_NO),
CONSTRAINT FK_OP_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));

CREATE TABLE SUPERVISE(
EMPL_ID CHAR(3),
SUP_EMPL_ID CHAR(3),
CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPL_ID,SUP_EMPL_ID),
CONSTRAINT FK_SUP_EMPLYOEES FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEES(EMPL_ID));



